### ISSUE TITLE
off-the-shelf configuration results in warnings

### ISSUE THREAD

**Issue by lianhao** [containers/nri-plugins#111]
I'm trying to run topology-aware nri-plugin, and using the off-the-shelf configurations from this git. However, I found the following warnings in the  topology-aware plugin log:

```
W0907 08:41:06.438974       1 resources.go:567] possible misconfiguration of reserved resources:
W0907 08:41:06.439054       1 resources.go:568]   root: allocatable <root allocatable: CPU: reserved:0 (allocatable: 51m), grantedReserved:949m, sharable:1-223 (allocatable:223000m), MemLimit: DRAM 1.97T>
W0907 08:41:06.439062       1 resources.go:569]   kube-system/nri-resource-policy-topology-aware-g5fxw/nri-resource-policy-topology-aware: needs 500 reserved, only 51 available
W0907 08:41:06.439067       1 resources.go:571]   falling back to using normal unreserved CPUs instead...
```

My environment is:
- Ubuntu 22.04 with kernel 5.15.0-83-generic
- containerd: v1.7.5
- nri-plugin: git commit c587af49982c6bfc3535dce57f8fc4e0dd44daeb
- K8S: v1.23.6, kubeadm setup, no special configuration, all out-of-box default configuration

May I ask what's the warning messages means? Does it matters?

**Comment by klihub** [comment]
The warning message means that the policy could not allocate, in this case for itself, CPUs from the `reserved` CPU set which are set aside for pods/containers in the kube-system namespace. The policy has a CPU request of 500m (IOW, half a CPU core) but there are only 51m left in the reserved CPU set. Therefore the policy decides to allocate CPUs from the rest of the CPUs instead of the reserved set.

This should not be anything extremely dangerous. The policy will share CPUs with a different, and potentially larger, set of workloads than it would in the reserved set, where it would share CPUs with the K8s control plane components. Here it will share CPUs with whatever other workloads end up being assigned to the same topology zone and its parent zones where the policy itself ended up getting assigned to.

If you want to get rid of this, a proper fix would be to increase the amount of (kube-system) reserved CPU at least by `(500 - 51)m = 449m` compared to your current reservation, and do it for both the kubelet and the policy.

For the policy you simply edit the configuration CR of the node, which in a default running setup can be done with `kubectl get -n kube-system topologyawarepolicies.config.nri/default` and updating `reservedResources` to have `cpu: 2000m`.

For kubelet, if you are on a fairly recent kubernetes (>= 1.30), it might be a good idea to enable drop-in configuration for kubelet and use a drop-in file on the system nodes. Moreover, if your nodes are hyperthreaded it might be a good idea to always reserved full physical cores IOW multiples of two logical CPUs. If your current reservation is <= 2000m CPU then just increate it to 2000m. 

All of these can be accomplished, for instance, by making sure kubelet is passed in a `--config-dir` argument to enable drop-ins, then using a drop-in to increase the kube-system reservation. For instance, if you run kubelet with `--config-dir /etc/kubernetes/kubelet.conf.d` then  this file would reserve 2 logical CPUs.

```shell
$ cat /etc/kubernetes/kubelet.conf.d/10-reserved.conf
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
kubeReserved:
  cpu: 2000m
```

You can check your current setting of kubelet with

```shell
$ kubeclt proxy &
$ curl --silent -X GET http://127.0.0.1:8001/api/v1/nodes/$(hostname)/proxy/configz | jq .kubeletconfig.kubeReserved
{
  "cpu": "2000m"
}
```
